"""Constants for the Sol-Ark 15K Modbus integration."""

DOMAIN = "solark15k"
PLATFORMS = ["sensor"]

CONF_SLAVE_ID = "slave_id"
CONF_INTER_REQUEST_DELAY = "inter_request_delay"
CONF_REQUEST_TIMEOUT = "request_timeout"
CONF_RETRIES = "retries"
CONF_CHUNK_SIZE = "chunk_size"  # Legacy option; retained for compatibility.

CONF_MIN_REQUEST_SPACING = "minimum_request_spacing"
CONF_LIVE_INTERVAL = "live_poll_interval"
CONF_FAULT_INTERVAL = "fault_poll_interval"
CONF_DETAIL_INTERVAL = "detail_poll_interval"
CONF_ENERGY_INTERVAL = "energy_poll_interval"

DEFAULT_PORT = 502
DEFAULT_SLAVE_ID = 1
DEFAULT_INTER_REQUEST_DELAY = 15.0
DEFAULT_REQUEST_TIMEOUT = 5.0
DEFAULT_RETRIES = 2
DEFAULT_CHUNK_SIZE = 8

DEFAULT_MIN_REQUEST_SPACING = 1.0
DEFAULT_LIVE_INTERVAL = 5.0
DEFAULT_FAULT_INTERVAL = 15.0
DEFAULT_DETAIL_INTERVAL = 60.0
DEFAULT_ENERGY_INTERVAL = 300.0

MIN_INTER_REQUEST_DELAY = 5.0
MAX_INTER_REQUEST_DELAY = 120.0
MIN_REQUEST_TIMEOUT = 2.0
MAX_REQUEST_TIMEOUT = 30.0
MIN_CHUNK_SIZE = 1
MAX_CHUNK_SIZE = 32

MIN_REQUEST_SPACING = 0.5
MAX_REQUEST_SPACING = 15.0
MIN_LIVE_INTERVAL = 2.0
MAX_LIVE_INTERVAL = 60.0
MIN_FAULT_INTERVAL = 5.0
MAX_FAULT_INTERVAL = 300.0
MIN_DETAIL_INTERVAL = 10.0
MAX_DETAIL_INTERVAL = 900.0
MIN_ENERGY_INTERVAL = 60.0
MAX_ENERGY_INTERVAL = 3600.0

# Inclusive register ranges used by the public Sol-Ark Modbus V1.4 map.
REGISTER_RANGES = (
    (60, 114),
    (150, 196),
)
